---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: backend-secret
  namespace: demo-app
spec:
  encryptedData:
    MYSQL_PASSWORD: AgBTVhuhIkUjrFMBRH/1q7HBLfa/lU5qkJBGxlwQ7EVwVnmofrUl0gb4BqNyUDiynneAHEorccCReP3CSpGVTZv2xpxxP/+6W8SnCIOngFMtAvyni6RHPUsFOdI2LYN3IAnBSpue/nNvHUsUUresyB4V6qgCzXNbGuDju5sfDOnf9P9ejN1GiQ5O4MqfBvoo4ZGqbvxbP1xXPS1N+gMJQDUC1HLKMjWJTc5PUNOr5yYzdburTbEdhQs/aVf69jNpJrqphcSuRGxE3dJ/T7dcS07DmEFWaiDG0pxWs0B+wT59ePij1IIsJ8JM31L87nFlGnQuOpSnoTOFAQvM4z9c7GNGyCHjwsJKARQcX5ptMuIa/qcTUjy8KDRHwvaHmC4RxckjXGh2ifyzA1nC0d6FZ0IgLyEd2+5f9GJgjFsspysdFoDUcRZ761/nqCJYQMJg1IhAoYItLpdFdFtk7GR8Yzmb8t+tBkpUEUwCyY6cQpZFWEKbS6Ek5wTG593pp6BRCtpn2O9jVQH+ejzEtye6dYT6YvtVFhlFi+1Q+dmUe4kNWb+eH5EA5q51tg3yOVKTTyOI8ap1YZTmfkcR3qXeFRsH2Dg67L5SRWZOVFTwuycL1FkmPhuj7ZKTqmqrtlM6i9IhngqYVGXFdLzYCcZFRxaUwT6cROMbcMRaCwBSf8nEe3h8RWcJejfJoW3pt7R4YO/8OtwdKs1iKioNQ93byP8=
  template:
    metadata:
      creationTimestamp: null
      name: backend-secret
      namespace: demo-app
    type: Opaque
