---
- name: Sealed Secret Setup
  hosts: localhost
  collections:
    - kubernetes.core
  tasks:
    - name: Add stable chart repo
      kubernetes.core.helm_repository:
        name: sealed-secrets
        repo_url: "https://bitnami-labs.github.io/sealed-secrets"
    - name: Deploy Argocd chart using values files on target
      kubernetes.core.helm:
        name: sealed-secrets
        chart_ref: sealed-secrets/sealed-secrets
        release_namespace: sealed-secrets
        create_namespace: true
        values_files:
          - ./values/sealed-secrets/values.yaml