---
- name: Argocd Setup
  hosts: localhost
  collections:
    - kubernetes.core
  tasks:
    - name: Add stable chart repo
      kubernetes.core.helm_repository:
        name: argo
        repo_url: "https://argoproj.github.io/argo-helm"
    - name: Deploy Argocd chart using values files on target
      kubernetes.core.helm:
        name: argocd
        chart_ref: argo/argo-cd
        release_namespace: argocd
        create_namespace: true
        values_files:
          - ./values/argocd/values.yaml
    - name: Deploy the demo application from local file
      kubernetes.core.k8s:
        state: present
        src: ./manifests/argocd/demo-application.yaml
