apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-init-script
  namespace: demo-app
data:
  init.sql: |
    CREATE DATABASE IF NOT EXISTS counter_db;
    USE counter_db;
    CREATE TABLE IF NOT EXISTS counter (
        id INT AUTO_INCREMENT PRIMARY KEY,
        count INT NOT NULL DEFAULT 0
    );
    INSERT INTO counter (count)
    VALUES (0);
    -- Create a new MySQL user
    CREATE USER 'user'@'%' IDENTIFIED BY 'pass';
    -- Grant privileges to the new user on the counter_db database
    GRANT ALL PRIVILEGES ON counter_db.* TO 'user'@'%';
    -- Flush privileges to apply changes
    FLUSH PRIVILEGES;
