apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-app
  namespace: argocd
spec:
  destination:
    namespace: demo-app
    server: https://kubernetes.default.svc
  project: default
  source:
    path: manifests/k8s
    repoURL: https://github.com/eistin/demo-app
    targetRevision: HEAD
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true